[package]
name = "me3_launcher"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.5.60", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.0.3"
windows = { version = "0.62.2", features = ["Win32_System_Console"] }
